version: '3.0'
services:
 angular:
  build: easycreditfront
  ports:
   - "4200:4200"

 express:
  build : back
  ports:
   - "3000:3000"
  links:
   - database

 database:
  image : postgres
  ports:
   - "5432:5432"